#!/bin/sh

set -efu

url="$(
	curl -s -X POST \
		--data '{"id": "", "method": "aria2.getGlobalStat"}' \
		http://localhost:6800/jsonrpc
)"

tellActive="$(curl -s -X POST \
	--data '{"id": "", "method": "aria2.tellActive"}' \
	http://localhost:6800/jsonrpc)"

emptyResponse='{"id":"","jsonrpc":"2.0","result":[]}'

getGlobalStat() {
	progression="$(
		awk '
	BEGIN {
		FS = "\""
	}

	{
		for (i = 1; i <= NF; ++i) {
			if ($i ~ /[0-9]/ && $i !~ /\./) {
				if (i == 14) {
					print $(i - 2) ":", $i / 1024 "k"
				} else {
					print $(i - 2) ":", $i
				}
			}
		}
	}
	' <<-EOF
			${url}
		EOF
	)"
	printf "%s\n" "${progression}"
}

case "$1" in
-t | --toggleDownloads)
	if [ "${tellActive}" = "${emptyResponse}" ]; then
		curl -s -X POST \
			--data '{"id": "", "method": "aria2.unpauseAll"}' \
			http://localhost:6800/jsonrpc >/dev/null 2>&1
	else
		curl -s -X POST \
			--data '{"id": "", "method": "aria2.pauseAll"}' \
			http://localhost:6800/jsonrpc >/dev/null 2>&1
	fi
	;;
-a | --addUri)
	curl -s -X POST \
		--data '{"id": "",
			"method": "aria2.addUri",
			"params": [["'"$2"'"]]}' \
		http://localhost:6800/jsonrpc >/dev/null 2>&1
	;;
-g | --getGlobalStat)
	getGlobalStat
	;;
*)
	printf 'Illegal option!\n'
	exit 1
	;;
esac
printf 'OK\n'
