#!/bin/sh

set -efu

cleanup() {
	/usr/bin/printf '\n' \
		>/home/pactrag/Programme/sysinfo/misc/ariaProgress
	/usr/bin/printf '0' >/tmp/ariaParserSwitch.txt
	/usr/bin/dunstify --timeout=1000 "ended"
	exit
}
trap cleanup EXIT

/usr/bin/printf '1' >/tmp/ariaParserSwitch.txt

/usr/bin/dunstify --timeout=1000 "started"

# this creates problem; everytime I try to run aria from this script things
# start to go wrong
# if [ -z "$(/usr/bin/pgrep -x aria2c)" ]; then
# 	/usr/bin/aria2c >/tmp/ariaParser.txt 2>&1 &
# fi

while true; do
	summary="$(
		/usr/bin/curl --silent --request POST \
			--data '{"id": "", "method": "aria2.tellActive"}' \
			http://localhost:6800/jsonrpc |
			/usr/bin/awk '
BEGIN {
	FS = "\""
	completedLength = 0
	downloadSpeed = 0
	totalLength = 0
}
{
	for (i = 1; i <= NF; ++i) {
		if ($i == "totalLength") {
			totalLength += $(i + 2)
		} else if ($i == "downloadSpeed") {
			downloadSpeed += $(i + 2)
		# there are two "completedLength", we have to match the right one 
		# and ignore the other that is not proceeded by a comma
		} else if ($i == "completedLength" && $(i - 1) == ",") {
			completedLength += $(i + 2)
		}
	}
}
END {
	if (totalLength == 0) {
		exit 1
	}
	printf "%.2fk | %s | %.2f%%",
	downloadSpeed / 1024, NR, (completedLength / totalLength) * 100
}
'
	)" || break
	dunstify "${summary}"
	/usr/bin/sleep 1
done
