#!/bin/sh

compile_latex() {
	pdf_file="${1%%.tex}".pdf
	pdflatex -file-line-error -halt-on-error -shell-escape\
		-interaction=batchmode -output-directory='/tmp/' "$1" || exit
	/usr/bin/mv "/tmp/${pdf_file}" .
	firefox "${pdf_file}"
}

compile_latex "$1"

# Do not sync if 'texcompile ./file' is provided instead of 'texcompile file'.
case "$1" in
    ./*)
	exit
    ;;
    *)
    ;;
esac

while true; do
	tail --quiet --lines=0 --follow=name "$1" 2>/dev/null |
	head --bytes=1
	compile_latex "$1"
done
