#!/usr/bin/gawk -f

function connect_last()
{
	cmd = "iwctl known-networks list"
	for (i = 0; i < 4; ++i) {
		cmd | getline
	}
	while ((cmd | getline) > 0 && $0) {
		ssid = $0
		last_connected = $0
		sub(/\s+\S+\s+[A-Z][a-z]{2}\s[0-9]{1,2},\s{1,2}[0-9]{1,2}:[0-9]{1,2}\s[AP]M\s+$/,
			"", ssid)
		sub(/^\s+/, "", ssid)
		sub(/.*    /, "", last_connected)
		sub(/ +$/, "", last_connected)
		mmddhhmm = timestamp_to_mmddhhmm(last_connected)
		print mmddhhmm
		print ssid
	}
	close(cmd)
	exit
}


function timestamp_to_mmddhhmm(date_string, date) {
	split(date_string, date, "[ :,]+")

	# It is better to use the ternary operator here since it is more
	# concise than a multiple ifs.
	date[1] = date[1] == "Jan" ? 1 : date[1] == "Feb" ? 2 :
	date[1] == "Mar" ? 3 : date[1] == "Apr" ? 4 : date[1] == "May" ? 5 :
	date[1] == "Jun" ? 6 : date[1] == "Jul" ? 7 : date[1] == "Aug" ? 8 :
	date[1] == "Sep" ? 9 : date[1] == "Oct" ? 10 : date[1] == "Nov" ? 11 :
	12

	if (date[5] == "PM") {
		date[3] += 12
	}

	return sprintf("%02d%02d%02d%02d", date[1], date[2], date[3], date[4])
}

BEGIN {
	LINT = "fatal"
	connect_last()
	exit

	cmd = "iwctl station wlan0 show"
	for (i = 0; i < 6; ++i) {
		cmd | getline
	}
	state = /disconnected$/ ? 0 : 1
	close(cmd)
	if (state) {
		system("iwctl station disconnect")
	} else {
		print 0
	}
}
